name: social-network-web-app
version: '3'

services:
  web:
    container_name: network-app
    build: 
      context: .
      dockerfile: Dockerfile

    # command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - ./.env
  
  db:
    container_name: network-app-db
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ./.env
    

volumes:
  db-data:

